volumes:
  db:
    driver: local
  redis_data:
    driver: local

services:
  db:
    platform: linux/amd64
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=hameed
      - POSTGRES_PASSWORD=Asmath2001
      - POSTGRES_DB=perp
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
